# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 11:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.FileField(default='no image selected', upload_to='blog_media'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 6, 11, 17, 29, 715682)),
        ),
    ]
