# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 11:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170506_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='body',
            field=models.TextField(default='Add Content'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 6, 11, 24, 33, 193732)),
        ),
    ]
