# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=500)),
                ('image', models.FileField(upload_to='carouse_media')),
                ('animation', models.CharField(choices=[('fadeInLeft', 'fadeInLeft'), ('fadeInUp', 'fadeInUp'), ('fadeInDown', 'fadeInDown'), ('fadeInRight', 'fadeInRight')], default='fadeInUp', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=150)),
                ('image', models.FileField(upload_to='ours_media')),
                ('more', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='panels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('more', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_by', models.CharField(max_length=100)),
                ('quote', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.TextField()),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
