# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170506_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='animation',
            field=models.CharField(choices=[('fadeInRight', 'fadeInRight'), ('fadeInUp', 'fadeInUp'), ('fadeInDown', 'fadeInDown'), ('fadeInLeft', 'fadeInLeft')], default='fadeInUp', max_length=100),
        ),
    ]
