# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170507_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='animation',
            field=models.CharField(choices=[('fadeInLeft', 'fadeInLeft'), ('fadeInRight', 'fadeInRight'), ('fadeInDown', 'fadeInDown'), ('fadeInUp', 'fadeInUp')], default='fadeInUp', max_length=100),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.FileField(default='Please, use images of the same sizes (dimensions)', upload_to='carouse_media'),
        ),
        migrations.AlterField(
            model_name='ours',
            name='image',
            field=models.FileField(default='Please, use images of the same sizes (dimensions)', upload_to='ours_media'),
        ),
    ]
