# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170507_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='animation',
            field=models.CharField(choices=[('fadeInUp', 'fadeInUp'), ('fadeInRight', 'fadeInRight'), ('fadeInLeft', 'fadeInLeft'), ('fadeInDown', 'fadeInDown')], default='fadeInUp', max_length=100),
        ),
    ]
