# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170512_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='animation',
            field=models.CharField(choices=[('fadeInRight', 'fadeInRight'), ('fadeInLeft', 'fadeInLeft'), ('fadeInDown', 'fadeInDown'), ('fadeInUp', 'fadeInUp')], default='fadeInUp', max_length=100),
        ),
    ]
