# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 11:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.FileField(default='no image selected', upload_to='publications_media')),
                ('date', models.DateField(default=datetime.datetime(2017, 5, 6, 11, 45, 25, 20229))),
                ('body', models.TextField(default='Add Content')),
            ],
        ),
    ]
