# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 18:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 7, 18, 42, 44, 642277)),
        ),
    ]
