# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 20:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20170507_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 7, 20, 28, 35, 915847)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.FileField(default='Please, use images of the same sizes (dimensions)', upload_to='publications_media'),
        ),
    ]
