# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 20:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20170507_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 7, 20, 30, 9, 720506)),
        ),
    ]
