# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_grids',
            name='image',
            field=models.FileField(default='Please, use images of the same sizes (dimensions)', upload_to='about_media'),
        ),
    ]
